# Generated by Django 4.1.2 on 2022-11-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_cart_book_customer_alter_book_name_alter_book_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='customer',
            new_name='category',
        ),
    ]
